### ISSUE TITLE
Wrong directory in updated settings.gradle

### ISSUE THREAD

**Issue by andon** [rnpm/rnpm-plugin-link#23]
When integrating the [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons) a wrong directory is in the updated **settings.gradle** file.
```
react-native init TestProject
cd TestProject
npm install --save react-native-vector-images
rnpm link
cat android/settings.gradle
```
The output is
```
rootProject.name = 'TestProject'
include ':app'
include ':react-native-vector-icons'
project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../../node_modules/react-native-vector-icons/android')
```
The last line should actually be:
`project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-vector-icons/android')
`

**Comment by grabbou** [comment]
Thanks for reporting. That is indeed our fault, it's been already fixed - waiting for @Kureev review and landing later today :)

**Comment by grabbou** [comment]
(Already in npm - version 1.5.3. `npm install -g rnpm` and check again when you have time!)

**Comment by Kureev** [comment]
thanks :heart:
