### ISSUE TITLE
Make MainActivity detection more solid

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm-plugin-link#26]
It's not a requirement to use new MainActivity pattern starting from React 0.18 and some people might still keep using the old one (I don't know why, but it can happen).

Instead of checking for react version, let's check if MainActivity class extends "Activity" (that's the old version) or "ReactActivity" (that's the new version). Will give us best answer.

**Comment by Kureev** [comment]
yeah, good proposal

**Comment by geof90** [comment]
Actually, instead of looking for the import pattern, can we look for the MainActivity class definition pattern instead? So e.g.

https://github.com/rnpm/rnpm-plugin-link/compare/master...geof90:patch-2

This would work for both <0.17 and >=0.18. We could easily just use the same file.

**Comment by Kureev** [comment]
But patches for main activity looks different for <0.17 and 0.18+ versions

**Comment by grabbou** [comment]
We could probably make only different `packagePatches` instead of having entire mainActivity patches that way.

**Comment by Kureev** [comment]
Yes, we can improve this by making a change scope more atomic. Instead of the whole file we can change only one part.

**Comment by geof90** [comment]
Yup, using different package patches but using the same import patch was what I was trying to suggest. My code sample was just to communicate the idea, its not working code :p

**Comment by grabbou** [comment]
@geof90 it's been a while since we discussed it, but would you still be interested in taking that? I am not that much into these patches @Kureev done but I quite like the idea of making it slicker!

**Comment by geof90** [comment]
sure, I'll take a look over the weekend!

**Comment by grabbou** [comment]
After great @Kureev work on patches and the general idea to deprecate them at some point (0.17 is really old and probably will be no longer used in like a year), we can close it and revisit if we will be about to add yet another `patch`.
