### ISSUE TITLE
settings.gradle patch not respecting single line multi project "includes"

### ISSUE THREAD

**Issue by geof90** [rnpm/rnpm-plugin-link#30]
The code in `makeSettingsPatch` will break existing `settings.gradle` configs where users happen to use single-line multi-project `include` statements, e.g.:

`include ':app', ':react-plugin'`

https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/makeSettingsPatch.js#L20

To address this, I propose simply appending the new include statements to the file instead of searching for `include ':app'` and replacing it. It simplifies the code and is much less error prone.

**Comment by geof90** [comment]
Since this is a small and simple change, I have done up an existing PR to with my proposed changes https://github.com/rnpm/rnpm-plugin-link/pull/31

**Comment by Kureev** [comment]
Nice! Thanks for your awesome contributions!

**Comment by Kureev** [comment]
#31 is merged, so I assume we can close this issue.

**Comment by geof90** [comment]
Cool! Any ETA on when the latest bits can be published on to NPM? We can't wait to start using your work!

**Comment by Kureev** [comment]
@geof90 published as `1.5.4`

**Comment by geof90** [comment]
@Kureev awesome!!

**Comment by grabbou** [comment]
So excited to see android going more stable!
