### ISSUE TITLE
[iOS] Deep modules link

### ISSUE THREAD

**Issue by jhen0409** [rnpm/rnpm-plugin-link#37]
I created a RN module, which uses react-native-fs, but the RNFS cannot link with rnpm, because this plugin just [check project package.json](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/link.js#L20).

Now I temporarily added `react-native-fs` dependency to project, but it not perfect.

**Comment by grabbou** [comment]
Hey - yeah, that's true. I think in that case it's reasonable to create your own `.xcodeproj` in your `RN module` that has react-native-fs linked (you can use rnpm link inside it before publishing) so your consumers can only link your module w/o figuring out what other dependencies they have not specified are doing in their project :)

**Comment by Kureev** [comment]
Good idea with xcodeproj, but what about Android? I think we need to add recursive traversing for rn module dependencies. I'll research this one.

**Comment by grabbou** [comment]
I don't think you have to do anything - since you link to `gradle` it handles nested deps itself, just like local podspec (Cocoapods) can fetch additional things for your module and link frameworks.

**Comment by Kureev** [comment]
Ok, so what's the next step on this one?

**Comment by Kureev** [comment]
Feel free to re-open if I missed something.

**Comment by grabbou** [comment]
> I think if we can workaround it on iOS and don't need to do anything for Android, then we can safely close it

I am not really sure, it's still a potential feature. I'd rather leave it opened as there's some work going on right now on making CocoaPods working on top of iOS part which is likely so solve that as well. I can't see a straightforward solution to this problem just yet, but don't mind keeping it here just for future reference.

**Comment by grabbou** [comment]
I've renamed the title as Android part is done :)

**Comment by Kureev** [comment]
I think we can create a generic task about support CocoaPods, Kotlin, Carthage etc. What do you think, @grabbou?

**Comment by grabbou** [comment]
It's a great idea! Though this specific issue can be solved in the user land by properly organising the xcodeproj structure. Having said so, I think we can close it for now (I know I said the opposite last time, but I've misunderstood the issue quite a bit)
