### ISSUE TITLE
Remove `fs-extra` dependency

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm-plugin-link#42]
Can we implement copySync with just standard `fs` ?

**Comment by grabbou** [comment]
master now uses promises, so we can use standard fs.

**Comment by grabbou** [comment]
Hint: https://gist.github.com/tkihira/3014700 - this looks worth investigating

**Comment by Kureev** [comment]
It's "In progress" more than 2 weeks. Any updates?

**Comment by grabbou** [comment]
Yes, that is to be closed. Not worth rewriting copySync logic.
