### ISSUE TITLE
Suggestion: Moving some common methods to core for reusability

### ISSUE THREAD

**Issue by ptmt** [rnpm/rnpm-plugin-link#6]
Would be nice to have some well-tested common methods somewhere in utils. This could reduce dependencies required by the plugin code. I'd like to have these:

`getPlist()` — to obtain parsed plist. I used the same code https://github.com/rnpm/rnpm-plugin-link/blob/master/src/ios/copyAssets.js#L13 here: https://github.com/ptmt/rnpm-plugin-apphub/blob/master/src/projectMetadata.js (potentially it's useful for `rnpm-plugin-build` plugin too).

`GLOB_EXCLUDE_PATTERN` or even `searchFile(template)` for searching files in project source directory. 

Related: https://github.com/rnpm/rnpm-plugin-link/pull/5

**Comment by grabbou** [comment]
Woah, I have to say your plugin looks really exciting! Yep, I do agree and the number of utils is only going to increase as long as we add in new things.

I think that the most reasonable approach would be to set up `rnpm-utils-ios` (just like `Cocoapods/xcodeproj` library) with all these methods extracted/defined.

The current state of `rnpm-plugin-link` is in a stable enough stage to be extracted, so if that's something that'd worked for you - let me know and we can do that.

**Comment by ptmt** [comment]
Another approach would be extending function `config` argument, like `config.getPlist() : ParsedPlist` or `config.getXcodeproj() : Pbxproj`, etc. 

Ok, let's see what code would be shared by another plugins, and extract it if needed.

**Comment by grabbou** [comment]
Do you find any other methods useful? I am thinking about publishing `rnpm-ios` with all files from `ios` folder except `register/unregisterNativeModule` and `link/unlinkAssets`.

**Comment by grabbou** [comment]
Let's extract that to `rnpmjs` when #45 is merged so we can also use uniq/union etc. in rnpm itself.

**Comment by grabbou** [comment]
I think for now you should be able to `require('rnpm-plugin-link/src/ios/<func>')`. We will extract it later (or expose properly), but since we are transitioning to react-native, we can't extract them at this point.
