### ISSUE TITLE
Android Native UI Components not detected

### ISSUE THREAD

**Issue by jbrodriguez** [rnpm/rnpm-plugin-link#60]
Hi, I tried to link https://github.com/kwaak/react-native-android-circles, but it didn't work.

I'm guessing the plugin checks for a package in the createNativeModules function, but not in the  createViewManagers function, which is where UI components need to be registered.

Hope you can support UI Components as well.

**Comment by grabbou** [comment]
I think it's because the structure of that dependency does not have android folder @Kureev? 

I think setting rnpm.android.sourceDir = './' in that repo package.json should make it working :)

I'll try to confirm that and will submit a patch to that repo later today

**Comment by Kureev** [comment]
I think we need to formulate some requirements for third-party-modules.

**Comment by grabbou** [comment]
They are quite simple on Android - `android` or `android/app` folder must be present. Otherwise you need to overwrite that. We could add in a note to Readme re that fact.

On iOS - it works with `anything`.

**Comment by grabbou** [comment]
I am going to close this - please contact the author to either move everything to `android` folder as the most of cummunity is following this pattern or provide a custom `rnpm` config so we can detect this (feel free to ping me in case you need any help with the latter).

Apart from that, the installation steps are the same and the fact it exposes `views`, not `modules` shouldn't affect that :)
