### ISSUE TITLE
Lazy poll for params

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm-plugin-link#61]
Currently, if you have 10 dependencies and each of them has params, rnpm will ask for them once, before even checking if they are already linked.

That means I'll have to answer all these questions every-time I run rnpm link.

We should poll for params inside `registerNativeModule` imo only for that specific dependency.

**Comment by Kureev** [comment]
I'll take care of that when I'll have a bit of time

**Comment by grabbou** [comment]
I think what you need to do is to poll inside `registerNativeModule` after `isLinked` stage. We can make it return a promise, since the wrapper `link` is already async :)

**Comment by Kureev** [comment]
👍

**Comment by grabbou** [comment]
My proposal is as follows:
- make `register<platform>dependency` async and poll for params only if dependency is not yet linked (see #63 pull request for a working solution)
- remove `dependency.config.params` and move it to `dependency.config.ios.params` and `dependency.config.android.params` because in most cases, I believe these tokens are different (would love an input from @lostintangent - they already defined `insert your token for Android` which makes me thinking that when we make iOS - they will ask for `iOS` separately)

The 2nd point is super important so that we do not ask for Android params when user does not have Android project. I haven't found a better solution for that other than removing top-level `dependency.config.params`. From my native experience, these are in most cases going to be different. Even if not - it's reasonable to separate them.

1st point is to avoid asking for params when module is already linked (happens currently) and imo is not the best UX possible.
