### ISSUE TITLE
Unlink on Android is broken

### ISSUE THREAD

**Issue by grabbou** [rnpm/rnpm-plugin-link#66]
Keeps saying `not linked`

**Comment by grabbou** [comment]
Updating `isInstalled` check as in this commit < > deletes `few` things, but still leaves:
- `include ':react-native-code-push'` in settings.gradle,
- new CodePush in `MainActivity.java`

the rest (including import paths) is properly removed.

**Comment by Kureev** [comment]
This one has been fixed by #70
