### ISSUE TITLE
rnpm link is not working on Android for similar name modules

### ISSUE THREAD

**Issue by cpunion** [rnpm/rnpm-plugin-link#72]
I have two modules named likes `react-native-foo` and `react-native-foo-bar`, if run `rnpm link react-native-foo-bar` then `rnpm link react-native-foo`, it works fine on iOS, but not linked `react-native-foo` on Android, outputs:
```
rnpm-link info Linking react-native-foo android dependency
rnpm-link info Android module react-native-foo is already linked
```

Environment:
```
node --version && npm --version && rnpm --version && react-native --version
v5.5.0
3.6.0
1.6.2
react-native-cli: 0.2.0
react-native: 0.23.1
```

**Comment by Kureev** [comment]
Yeah, indeed. I'll do my best to fix it asap.

**Comment by grabbou** [comment]
Is that @Kureev handled by your branch yet?

**Comment by Kureev** [comment]
it would be

**Comment by Kureev** [comment]
fixed

**Comment by cpunion** [comment]
Great! Thanks @Kureev

**Comment by Kureev** [comment]
Can you update `rnpm` and try to reproduce it, @cpunion?

**Comment by cpunion** [comment]
@Kureev Just tested `rnpm@1.6.5` with `rnpm-plugin-link@1.7.3`, first run `rnpm link react-native-foo-bar` first, and then `rnpm link react-native-foo`, a problem in `android/settings.gradle`:

```
rootProject.name = 'TestRNPM'

include ':app'
include ':react-native-foo'
project(':react-native-foo').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-foo/android')include ':react-native-foo-bar'
project(':react-native-foo-bar').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-foo-bar/android')
```

`include ':react-native-foo-bar'` should in new line.

**Comment by grabbou** [comment]
So looks like the original issue is resolved, related issue to the `include` is here https://github.com/rnpm/rnpm/issues/153
