### ISSUE TITLE
Cannot add Frameworks group and system framework

### ISSUE THREAD

**Issue by andpor** [rnpm/rnpm-plugin-link#74]
This script is supposed to run postlink. It does not do anything - project is unchanged. This is running latest rnpm 1.6.2

```js
#!/usr/bin/env node

'use strict';

var fs = require('fs');
var rnpm = require('rnpm/src/config');
var xcode = require('xcode');
var createGroup = require('../../src/ios/createGroup');

var config = rnpm.getProjectConfig();


if (config.ios) {
    var pbxproj = config.ios.pbxprojPath;
    var project = xcode.project(pbxproj).parseSync();
    var target = project.getFirstTarget().uuid;

    //createGroup(project,'Frameworks');
    //project.addFramework('libsqlite3.0.tbd');

    Create a Frameworks group if necessary.
    if (!project.pbxGroupByName('Frameworks')) {
        //console.log("Frameworks not found, creating it ...")
        var group = project.pbxCreateGroup('Frameworks', '""');
        var mainGroup = project.getFirstProject().firstProject.mainGroup;
        //console.log(mainGroup);
        project.getPBXGroupByKey(mainGroup).children.push({
            value: group,
            comment: 'Frameworks',
        });
    }

    ['libsqlite3.0'].forEach(function(name) {
        project.addFramework('usr/lib/' + name + '.tbd', {
            lastKnownFileType: 'sourcecode.text-based-dylib-definition',
            sourceTree: 'SDKROOT',
            target: target,
        });
    });


    fs.writeFileSync(pbxproj, project.writeSync());
}
```

**Comment by Kureev** [comment]
So, inside package.json in your library you have this:
```json
"rnpm": {
  "commands": {
    "postlink": "./some/path/to/file"
  }
}
```
and in the some/path/to/file you have a code snippet that you posted here, right?

Are you sure that file isn't called at all?
Which error(s) do you have?

**Comment by andpor** [comment]
Yes, precisely. I see no errors which is part of the problem because obviously there are issues. Having adjusted the NODE_PATH I managed to get a module not found 'xcode' error which is weird because that is a installed dependency of rnpm. When I npm link xcode locally to the project, I got the postlink to work finally. However, not sure why I need to local link the xcode module...

How do I log stuff out of my postlink.js

I am using nvm with node 4.1 on Mac OS X

**Comment by Kureev** [comment]
> not found 'xcode' error which is weird because that is a installed dependency of rnpm.

It is, but we spawn a separated processes for rnpm commands, so I'm not sure where it tries to find missing modules. Most probably, it tries to find it in the folder where you run `rnpm` command (i.e. your project dir), so it checks nearest node_modules folder.

**Comment by andpor** [comment]
rnpm is installed globally...and so i the dependent xcode...

**Comment by grabbou** [comment]
In that case either `npm install -g xcode` or install `rnpm` locally so xcode is present in the node_modules (which is just because of npm3 flattening the tree. Generally if you want to use it - you should declare it as a dependency of your module).

**Comment by andpor** [comment]
Thanks!
