### ISSUE TITLE
build.gradle patching doesn't accomodate multiple dependencies statements

### ISSUE THREAD

**Issue by lostintangent** [rnpm/rnpm-plugin-link#75]
If an app's `build.gradle` file includes a `buildscript.dependencies` block (e.g. because they're using [Crashlytics](https://fabric.io/kits/android/crashlytics/install) which instructs you to add it), which appears before the project's `dependencies` block, then the current [patch script](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/makeBuildPatch.js#L8) will add the linked module's `compile project()` statement to it instead of the project's `dependencies` block.

```gradle
buildscript {
    dependencies { 
       // Dependency gets placed here
    }
}

dependencies {
   // Should go here
}
```

There may be other scenarios where this could be an issue, but in general, it seems like the `makeBuildPatch.js` pattern might need to be made a little more specific. We had a CodePush user run into this issue, but it seems generic to any module that is being linked to a project that has a `build.gradle` file that matches this criteria.

**Comment by Kureev** [comment]
I'll try to look on this today. Unfortunately, it seems I'll have to write a parser for gradle files, otherwise I wouldn't be able to distinguish a proper dependencies block.

**Comment by geof90** [comment]
@Kureev We used https://www.npmjs.com/package/gradle-to-js in our CLI with some success, you might want to take a look!

**Comment by Kureev** [comment]
@geof90 You saved my day, bro 👍 I think we can use it! Or, at least, I can fork it and add missing functionality

**Comment by Kureev** [comment]
@geof90 mb you know something for json2gradle? :)

**Comment by geof90** [comment]
I don't know anything about json2gradle haha. For gradle-to-js, I had to fork it too because there's some bugs (e.g. it will parse appVersion "1.0" as the JS number "1" because of its naive way of checking whether something can be parsed as a number).

**Comment by Kureev** [comment]
I'm afraid I need to read -> patch -> write, so I need to convert JSON back to gradle config

**Comment by grabbou** [comment]
Can we make a more subtle regexp for finding block that will ignore nested searches?

**Comment by Kureev** [comment]
Unfortunately, the only way to improve regexp is to hardcode amount of spaces around `dependencies {`, but I'd like to come up with a better solution for it.

**Comment by grabbou** [comment]
I've encountered this earlier today and decided to give it a go! From my internal testing looks like that patch works well.
