### ISSUE TITLE
project is not defined

### ISSUE THREAD

**Issue by sibeliusseraphini** [rnpm/rnpm-plugin-link#76]
```js
rnpm/node_modules/rnpm-plugin-link/src/link.js:101
    project.assets
    ^

ReferenceError: project is not defined
    at Object.link (rnpm/node_modules/rnpm-plugin-link/src/link.js:101:5)
    at Command.runAction (rnpm/bin/cli:21:15)

```

This is happening with node v6

**Comment by grabbou** [comment]
I think that was Node 5 quirk that the constant was going out of try/catch scope. If you could replace let with var in your PR as the tests are running on Node 5 that doesn't accept top level let outside strict mode - it'd be cool.
