### ISSUE TITLE
link.js throw exception in node v6.0

### ISSUE THREAD

**Issue by holmescn** [rnpm/rnpm-plugin-link#78]
rnpm-plugin-link 1.7.2, node v6.0.0, link.js:86. The const project is created in try block, so it cannot accessed by the following code outside try-catch block. I have rewritten it to:

    let project;
    try {
      project = config.getProjectConfig();
    } catch (err) {
      log.error('ERRPACKAGEJSON', `No package found. Are you sure it's a React Native project?`);
      return Promise.reject(err);
    }

I am to lazy to create a PR ^_^.

**Comment by grabbou** [comment]
I ma pretty sure I already answered in different repo. Fix hitting npm later today.

**Comment by sibeliusseraphini** [comment]
@holmescn fixed with this PR https://github.com/rnpm/rnpm-plugin-link/pull/77

**Comment by grabbou** [comment]
Released, please upgrade `rnpm` :)
