### ISSUE TITLE
Android param patch incorrectly references R.strings

### ISSUE THREAD

**Issue by lostintangent** [rnpm/rnpm-plugin-link#86]
We had someone log a bug with CodePush that seems to be due to the fact that RNPM refers to ["R.strings"](https://github.com/rnpm/rnpm-plugin-link/blob/master/src/android/patches/applyParams.js#L10) instead of "R.string" when generating the code for a configured param that is referenced in a plugin's packageInstance setting.

I haven't had a chance to look into it yet, but it seems like [R.string](https://developer.android.com/reference/android/R.string.html) is in fact the correct member name.

**Comment by grabbou** [comment]
True, mind sending a pull request? cc: @Kureev

**Comment by Kureev** [comment]
Oops. I'm wondering why nobody reported this before 😮

**Comment by lostintangent** [comment]
Yep I can send a PR later this evening when I get home. Thanks guys!

**Comment by Kureev** [comment]
I've made a PR to fix this issue. Please, take a look
