### ISSUE TITLE
not support react-native 0.29.0 

### ISSUE THREAD

**Issue by lotosbin** [rnpm/rnpm-plugin-link#95]
https://github.com/facebook/react-native/releases/tag/v0.29.0

Android

 application template has changed.

**Comment by jhen0409** [comment]
It's fixed by https://github.com/facebook/react-native/commit/214a41d62af6c752bf34e40bc0b046790a009e3d (v0.29.1), and we should use `react-native link` instead of `rnpm link` for now.

**Comment by Kureev** [comment]
When https://github.com/facebook/react-native/issues/8623 will be merged, we deprecate this repo and continue development inside RN. If you don't any complex cases, please, use `react-native link` instead.
