### ISSUE TITLE
Pass params to postlink

### ISSUE THREAD

**Issue by geof90** [rnpm/rnpm-plugin-link#96]
`rnpm link`/`react-native link` is great, however there are some patches specific to our plugin that developers need to make when instrumenting their app with our plugin. We intend to automate these extra steps for them in a `postlink` script.

Some of these patches require information that the user needs to provide to us (in our case, a deployment key). We tried to do something like this to prompt the user for the key:

``` json
{
  "rnpm": {
    "params": [
      {
        "message": "What is your CodePush deployment key for iOS (hit <ENTER> to ignore)",
        "name": "iosDeploymentKey",
        "type": "input"
      }
    ],
    "commands": {
      "postlink": "rnpm codepushify-ios ${iosDeploymentKey}"
    }
  }
}
```

However, the `${iosDeploymentKey}` syntax doesn't actually get replaced with the key when our script is called. The alternative is for us to poll for that additional param ourselves, but it would be great if we can add support for parameterized strings in the `postlink` declaration.

**Comment by Kureev** [comment]
Hi @geof90! Thanks for the warm words about `link`.

About your request: tbh, we didn't expect people to use postlink hooks and parameters this way :) I don't have any ideas about it now. Parametrization is an experimental feature that we implemented only for Android (iOS version is on the roadmap). I'll try to keep you posted (and of course, we'll keep in mind your feature request).

**Comment by Kureev** [comment]
wdyt, @grabbou?
